spring:
  application:
    name: marketinsights

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.h2.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

  flyway:
    enable: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

marketinsights:
  security:
    secret: ${SECRET}
