spring:
  application:
    name: marketinsights

  datasource:
    url: jdbc:h2:file:./data/marketinsightsdb
#    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
#      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true

  flyway:
    enable: true
    locations: classpath:db/migration
    baseline-on-migrate: true

#spring.application.name=marketinsights
#
#spring.datasource.url=
#spring.datasource.driver-class-name=
#spring.datasource.username=
#spring.datasource.password=
#
## Configurações do JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.h2.console.enabled=true
#
## Configurações do flyway
#spring.flyway.enable=true
#spring.flyway.locations=classpath:db/migrations
#spring.flyway.baseline-on-migrate=true
